Wiki.dokuwiki byt3 - makes wiki of toolbox available via toolbox-website - as commonly agreed
ToolboxBodensee/toolbox-webseite pull request #469
Opened 2019-11-25 10:58 UTC by rtt-mmk

macht das Wiki wieder an gewohnter Stelle auf der Webseite aufrufbar

auf Dauer wäre es sicher besser wiki.tbbs.me und tbbs.me verweisen per DNS direkt auf das dokuwiki...wie schon vor über einer Woche vorgeschlagen. Und hier im Webseite-Code wird darauf verlinkt.

2019-11-25 11:38 UTC, 205er commented
Ich fänd's besser, wenn der Link auf eine offizielle Toolbox-Domain zeigt.
Unser Webseiten-Beirat @maxbachmann ist momentan schon dabei sich um Infrastruktur zu kümmern. Dauert also noch etwas, bis Wiki und Webseite ein neues Zuhause haben.

2019-11-26 09:35 UTC, maxbachmann commented
Das wiki ist jetzt auch wieder unter https://wiki.toolbox-bodensee.de/ erreichbar.
@rtt-mmk Kannst du den PR gleich auf gitlab stellen, du hast dort ja auch bereits Zugriff.

2019-11-26 12:01 UTC, 205er requested changes
bitte auf [wiki.toolbox-bodensee.de](https://wiki.toolbox-bodensee.de) verlinken

2019-11-28 21:54 UTC, rtt-mmk commented
ähh, ich hab das jetzt auch gerade auf Gitlab eingepflegt - wo soll das jetzt gemergt werden? Oder auf beiden?

2019-11-28 21:54 UTC, maxbachmann commented
nur auf gitlab und wird dann von gitlab hierher gemirrort. Ich werde bei den Repos gleich auch noch ein entsprechendes Kommentar einfügen

2019-11-28 21:56 UTC, rtt-mmk commented
ok. ist done auf Gitlab - braucht dort halt jetzt die approvals

2019-11-28 21:56 UTC, maxbachmann commented
ja habe ich gemergt

2019-11-28 21:57 UTC, closed without merging